export const POSTS_LIST = [
    {
        id: 1,
        image: 'https://image.shutterstock.com/image-photo/mountains-under-mist-morning-amazing-260nw-1725825019.jpg',
        text: 'Some text',
        date: '2021-10-06',
        isFavorite: true,
    },
    {
        id: 17,
        image: 'https://image.shutterstock.com/image-photo/mountains-under-mist-morning-amazing-260nw-1725825019.jpg',
        text: 'Some text',
        date: '2021-10-06',
        isFavorite: false,
    },

    {
        id: 5,
        image: 'https://image.shutterstock.com/image-photo/mountains-under-mist-morning-amazing-260nw-1725825019.jpg',
        text: 'Some text',
        date: '2021-10-06',
        isFavorite: true,
    },
    {
        id: 18,
        image: 'https://image.shutterstock.com/image-photo/mountains-under-mist-morning-amazing-260nw-1725825019.jpg',
        text: 'Some text',
        date: '2021-10-06',
        isFavorite: false,
    },
    {
        id: 6,
        image: 'https://image.shutterstock.com/image-photo/mountains-under-mist-morning-amazing-260nw-1725825019.jpg',
        text: 'Some text',
        date: '2021-10-06',
        isFavorite: true,
    },
    {
        id: 7,
        image: 'https://image.shutterstock.com/image-photo/mountains-under-mist-morning-amazing-260nw-1725825019.jpg',
        text: 'Some text',
        date: '2021-10-06',
        isFavorite: true,
    },
    {
        id: 8,
        image: 'https://image.shutterstock.com/image-photo/mountains-under-mist-morning-amazing-260nw-1725825019.jpg',
        text: 'Some text',
        date: '2021-10-06',
        isFavorite: false,
    },
    {
        id: 9,
        image: 'https://image.shutterstock.com/image-photo/mountains-under-mist-morning-amazing-260nw-1725825019.jpg',
        text: 'Some text',
        date: '2021-10-06',
        isFavorite: true,
    },
    {
        id: 10,
        image: 'https://image.shutterstock.com/image-photo/mountains-under-mist-morning-amazing-260nw-1725825019.jpg',
        text: 'Some text',
        date: '2021-10-06',
        isFavorite: true,
    },
    {
        id: 11,
        image: 'https://image.shutterstock.com/image-photo/mountains-under-mist-morning-amazing-260nw-1725825019.jpg',
        text: 'Some text',
        date: '2021-10-06',
        isFavorite: true,
    },
    {
        id: 12,
        image: 'https://image.shutterstock.com/image-photo/mountains-under-mist-morning-amazing-260nw-1725825019.jpg',
        text: 'Some text',
        date: '2021-10-06',
        isFavorite: false,
    },
    {
        id: 13,
        image: 'https://image.shutterstock.com/image-photo/mountains-under-mist-morning-amazing-260nw-1725825019.jpg',
        text: 'Some text',
        date: '2021-10-06',
        isFavorite: false,
    },
    {
        id: 14,
        image: 'https://image.shutterstock.com/image-photo/mountains-under-mist-morning-amazing-260nw-1725825019.jpg',
        text: 'Some text',
        date: '2021-10-06',
        isFavorite: false,
    },
    {
        id: 16,
        image: 'https://image.shutterstock.com/image-photo/mountains-under-mist-morning-amazing-260nw-1725825019.jpg',
        text: 'Some text',
        date: '2021-10-06',
        isFavorite: false,
    },
    {
        id: 2,
        image: 'https://image.shutterstock.com/image-photo/mountains-under-mist-morning-amazing-260nw-1725825019.jpg',
        text: 'Some text',
        date: '2021-10-06',
        isFavorite: true,
    },
    {
        id: 3,
        image: 'https://image.shutterstock.com/image-photo/mountains-under-mist-morning-amazing-260nw-1725825019.jpg',
        text: 'Some text',
        date: '2021-10-06',
        isFavorite: true,
    },
    {
        id: 15,
        image: 'https://image.shutterstock.com/image-photo/mountains-under-mist-morning-amazing-260nw-1725825019.jpg',
        text: 'Some text',
        date: '2021-10-06',
        isFavorite: false,
    },
    {
        id: 4,
        image: 'https://image.shutterstock.com/image-photo/mountains-under-mist-morning-amazing-260nw-1725825019.jpg',
        text: 'Some text',
        date: '2021-10-06',
        isFavorite: true,
    },
    {
        id: 19,
        image: 'https://image.shutterstock.com/image-photo/mountains-under-mist-morning-amazing-260nw-1725825019.jpg',
        text: 'Some text',
        date: '2021-10-06',
        isFavorite: false,
    },
];
